// <auto-generated />
using System;
using Arqsi_1160752_1161361_3DF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Arqsi_1160752_1161361_3DF.Migrations
{
    [DbContext(typeof(ClosetContext))]
    partial class ClosetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int?>("ParentCategoryID");

                    b.HasKey("ID");

                    b.HasIndex("ParentCategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Finish", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FinishName");

                    b.Property<int?>("MaterialID");

                    b.HasKey("ID");

                    b.HasIndex("MaterialID");

                    b.ToTable("Finishes");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Float", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DiscretePossibleValuesID");

                    b.Property<float>("FloatValue");

                    b.HasKey("ID");

                    b.HasIndex("DiscretePossibleValuesID");

                    b.ToTable("Float");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Material", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaterialName");

                    b.HasKey("ID");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.PossibleDimensions", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepthPossibleValuesID");

                    b.Property<int>("HeightPossibleValuesID");

                    b.Property<int>("WidthPossibleValuesID");

                    b.HasKey("ID");

                    b.HasIndex("DepthPossibleValuesID");

                    b.HasIndex("HeightPossibleValuesID");

                    b.HasIndex("WidthPossibleValuesID");

                    b.ToTable("PossibleDimensions");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.PossibleValues", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("PossibleValues");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PossibleValues");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("PossibleDimensionsID");

                    b.Property<float>("Price");

                    b.Property<int>("ProductCategoryID");

                    b.HasKey("ID");

                    b.HasIndex("PossibleDimensionsID");

                    b.HasIndex("ProductCategoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.ProductMaterialRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaterialId");

                    b.Property<int>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMaterialRelationships");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.ProductRelationship", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChildProductID");

                    b.Property<bool>("IsMandatory");

                    b.Property<int>("ParentProductID");

                    b.HasKey("ID");

                    b.HasIndex("ChildProductID");

                    b.HasIndex("ParentProductID");

                    b.ToTable("ProductRelationships");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Restriction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("ProductRelationshipID");

                    b.HasKey("ID");

                    b.HasIndex("ProductRelationshipID");

                    b.ToTable("Restriction");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Restriction");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.ContinuousPossibleValues", b =>
                {
                    b.HasBaseType("Arqsi_1160752_1161361_3DF.Models.PossibleValues");

                    b.Property<float>("MaxValue");

                    b.Property<float>("MinValue");

                    b.ToTable("ContinuousPossibleValues");

                    b.HasDiscriminator().HasValue("ContinuousPossibleValues");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.DiscretePossibleValues", b =>
                {
                    b.HasBaseType("Arqsi_1160752_1161361_3DF.Models.PossibleValues");


                    b.ToTable("DiscretePossibleValues");

                    b.HasDiscriminator().HasValue("DiscretePossibleValues");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.DimensionsRestriction", b =>
                {
                    b.HasBaseType("Arqsi_1160752_1161361_3DF.Models.Restriction");

                    b.Property<float>("MaxDepthValue");

                    b.Property<float>("MaxHeightValue");

                    b.Property<float>("MaxWidthValue");

                    b.Property<float>("MinDepthValue");

                    b.Property<float>("MinHeightValue");

                    b.Property<float>("MinWidthValue");

                    b.ToTable("DimensionsRestriction");

                    b.HasDiscriminator().HasValue("DimensionsRestriction");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.MaterialRestriction", b =>
                {
                    b.HasBaseType("Arqsi_1160752_1161361_3DF.Models.Restriction");


                    b.ToTable("MaterialRestriction");

                    b.HasDiscriminator().HasValue("MaterialRestriction");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.PercentageRestriction", b =>
                {
                    b.HasBaseType("Arqsi_1160752_1161361_3DF.Models.Restriction");

                    b.Property<float>("MaxDepthPercentage");

                    b.Property<float>("MaxHeightPercentage");

                    b.Property<float>("MaxWidthPercentage");

                    b.Property<float>("MinDepthPercentage");

                    b.Property<float>("MinHeightPercentage");

                    b.Property<float>("MinWidthPercentage");

                    b.ToTable("PercentageRestriction");

                    b.HasDiscriminator().HasValue("PercentageRestriction");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Category", b =>
                {
                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.Category", "ParentCategory")
                        .WithMany("ChildCategory")
                        .HasForeignKey("ParentCategoryID");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Finish", b =>
                {
                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.Material")
                        .WithMany("AvailableFinishes")
                        .HasForeignKey("MaterialID");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Float", b =>
                {
                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.DiscretePossibleValues")
                        .WithMany("PossibleValues")
                        .HasForeignKey("DiscretePossibleValuesID");
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.PossibleDimensions", b =>
                {
                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.PossibleValues", "DepthPossibleValues")
                        .WithMany()
                        .HasForeignKey("DepthPossibleValuesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.PossibleValues", "HeightPossibleValues")
                        .WithMany()
                        .HasForeignKey("HeightPossibleValuesID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.PossibleValues", "WidthPossibleValues")
                        .WithMany()
                        .HasForeignKey("WidthPossibleValuesID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Product", b =>
                {
                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.PossibleDimensions", "PossibleDimensions")
                        .WithMany()
                        .HasForeignKey("PossibleDimensionsID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.Category", "ProductCategory")
                        .WithMany()
                        .HasForeignKey("ProductCategoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.ProductMaterialRelationship", b =>
                {
                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.ProductRelationship", b =>
                {
                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.Product", "ChildProduct")
                        .WithMany()
                        .HasForeignKey("ChildProductID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.Product", "ParentProduct")
                        .WithMany()
                        .HasForeignKey("ParentProductID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Arqsi_1160752_1161361_3DF.Models.Restriction", b =>
                {
                    b.HasOne("Arqsi_1160752_1161361_3DF.Models.ProductRelationship")
                        .WithMany("Restrictions")
                        .HasForeignKey("ProductRelationshipID");
                });
#pragma warning restore 612, 618
        }
    }
}
